### PR TITLE
options `-h`/`--help` should not exit with failure

### PR DESCRIPTION
**Pull request by DrYak**
Here's the pull request, as discussed with @SoapZA in [pull #6814](https://github.com/bioconda/bioconda-recipes/pull/6814#pullrequestreview-77074490) of bioconda.

### CODE REVIEW

**Comment by SoapZA** [comment]
@DrYak have you checked formatting with `clang-format -style=file -i src/shorah/*.[ch]pp`?

**Comment by DrYak** [comment]
Doesn't produce any change.
(I presume my edits pass the style ? Either that, or I've utterly broken my clang installation)

**Comment by DrYak** [comment]
Thanks fore the merge! 

Could you also please tag and release v1.1.2 (unless there are some other modifications that you wanted to keep for that version) ?

Thank you in advance.

**Comment by SoapZA** [comment]
@DrYak done, please also update the bioconda one.

**Comment by DrYak** [comment]
[Here](https://github.com/bioconda/bioconda-recipes/pull/6824) you are.

**Pull request merged**
